# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a3ac058a53ebfb7256cfc743e94ba6847782c042522b242a7665d7832063e06891ed243f00f0db677ff04d9f5613b9a4c5e5e7ec0c4ba6e5d327304d1e83b5

test:
  secret_key_base: e47f8ef0fd827116767cf2b610698ec4e0484023b174542610622d6d8c34e4173fb5d3e8104413aa1f11808bc90737f64993ea4c20e40c89545a5aff33586d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
